# coding: utf-8

"""
    LocationIQ

    LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import locationiq
from locationiq.models.namedetails import Namedetails  # noqa: E501
from locationiq.rest import ApiException


class TestNamedetails(unittest.TestCase):
    """Namedetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNamedetails(self):
        """Test Namedetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = locationiq.models.namedetails.Namedetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
