# coding: utf-8

"""
    LocationIQ

    LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import locationiq
from locationiq.api.reverse_api import ReverseApi  # noqa: E501
from locationiq.rest import ApiException


class TestReverseApi(unittest.TestCase):
    """ReverseApi unit test stubs"""

    def setUp(self):
        self.api = locationiq.api.reverse_api.ReverseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reverse(self):
        """Test case for reverse

        Reverse Geocoding  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
