# coding: utf-8

"""
    LocationIQ

    LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.  # noqa: E501

    OpenAPI spec version: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import locationiq
from locationiq.models.balance import Balance  # noqa: E501
from locationiq.rest import ApiException


class TestBalance(unittest.TestCase):
    """Balance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalance(self):
        """Test Balance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = locationiq.models.balance.Balance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
