# coding: utf-8

"""
    LocationIQ

    LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import locationiq
from locationiq.api.autocomplete_api import AutocompleteApi  # noqa: E501
from locationiq.rest import ApiException


class TestAutocompleteApi(unittest.TestCase):
    """AutocompleteApi unit test stubs"""

    def setUp(self):
        self.api = locationiq.api.autocomplete_api.AutocompleteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_autocomplete(self):
        """Test case for autocomplete

        """
        pass


if __name__ == '__main__':
    unittest.main()
